name       : perl-dbi
version    : 1.641
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/T/TI/TIMB/DBI-1.640.tar.gz : 327e1bd92cd8ca2539b307b6d8c9d9527e5e707da99b87d52020841bc049a14a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Database independent interface for Perl
description: |
    The DBI is the standard database interface module for Perl. It defines a set of methods, variables and conventions that provide a consistent database interface independent of the actual database being used.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test #TEST_VERBOSE=1
