name       : perl-dbi
version    : '1.643'
release    : 13
source     :
    - https://cpan.metacpan.org/authors/id/T/TI/TIMB/DBI-1.643.tar.gz : 8a2b993db560a2c373c174ee976a51027dd780ec766ae17620c20393d2e836fa
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Database independent interface for Perl
description: |
    The DBI is the standard database interface module for Perl. It defines a set of methods, variables and conventions that provide a consistent database interface independent of the actual database being used.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test #TEST_VERBOSE=1
