name       : perl-dbi
version    : 1.636
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/T/TI/TIMB/DBI-1.636.tar.gz : 8f7ddce97c04b4b7a000e65e5d05f679c964d62c8b02c94c1a7d815bb2dd676c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Database independent interface for Perl
description: |
    Database independent interface for Perl.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
