name       : perl-dbi
version    : '1.637'
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/T/TI/TIMB/DBI-1.637.tar.gz : 2557712593e80142c3b50877e00369b6ce78fa26d44edc42156d81a5cdd26bc6
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Database independent interface for Perl
description: |
    Database independent interface for Perl.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test #TEST_VERBOSE=1
